/**
 * Part 1 of the Data Pipeline series — "From the whole internet to a recipe".
 * The walkable end-to-end story: 9 nodes across the 4-station backbone. Nodes
 * are re-homed (not rewritten) from the source lessons — web-scale ingestion
 * (N1–N3), domain sources (N1), deduplication (N1, N5) and data recipe
 * (N1, N4, N6). The shell copy (hero, stations, explain, bridge, nav) lives
 * here; each node carries its own control-label bundle in `ui`.
 *
 * See app/components/DataPipeline.tsx for the rendering and app/lib/{webscale,
 * domains,dedup,recipe}.ts for the (imported, un-duplicated) node logic.
 */

import type { PipelineLesson, PipelineNode } from "./pipeline-shell";

const STATIONS_EN = [
  { key: "gather", label: "GATHER", title: "Gather the raw web", blurb: "Rank the whole web by authority and keep only the top slice — before fetching a single byte." },
  { key: "extract", label: "EXTRACT & ENRICH", title: "Extract & enrich", blurb: "Strip pages down to clean text, then blend in denser sources — code, maths and books." },
  { key: "dedup", label: "DEDUPLICATE", title: "Strip the repeats", blurb: "Remove exact, near, and reworded copies so the model learns instead of memorising." },
  { key: "recipe", label: "THE RECIPE", title: "Blend the recipe", blurb: "Decide how much of each kind of text — and manufacture more of the dense stuff when it runs out." },
];

const STATIONS_ES = [
  { key: "gather", label: "RECOLECTAR", title: "Recolectar la web cruda", blurb: "Ordena toda la web por autoridad y quédate solo con la mejor franja — antes de descargar un solo byte." },
  { key: "extract", label: "EXTRAER Y ENRIQUECER", title: "Extraer y enriquecer", blurb: "Reduce las páginas a texto limpio y luego mezcla fuentes más densas — código, matemáticas y libros." },
  { key: "dedup", label: "DEDUPLICAR", title: "Quitar las repeticiones", blurb: "Elimina copias exactas, casi-iguales y reescritas para que el modelo aprenda en vez de memorizar." },
  { key: "recipe", label: "LA RECETA", title: "Mezclar la receta", blurb: "Decide cuánto de cada tipo de texto — y fabrica más del denso cuando se agota." },
];

const NODES_EN: PipelineNode[] = [
  /* ------------------------------------------------ GATHER · 1 (web-scale N1) */
  {
    station: "gather",
    eyebrow: "GATHER · STEP 1",
    title: "Which domains even get crawled",
    intro: "You can't crawl the whole web on a fixed budget — so before fetching anything, a lab ranks domains by authority and keeps only the top slice.",
    bullets: [
      "**Authority is a [PageRank](https://en.wikipedia.org/wiki/PageRank)-style score** over inbound links. High-authority hubs — [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia), GitHub, arXiv — sit near the centre.",
      "**The {ring} green ring is the threshold.** Inside is kept as a seed; outside is dropped *before a single byte is fetched* — the highest-leverage number in the pipeline.",
      "**Pages come from 4 tiers** — toggle each below:",
      "  **T1 · Common Crawl** — the free public snapshot of the web. Most of the volume, no cost.",
      "  **T2 · In-house bots** — the lab's own crawlers (GPTBot, ClaudeBot): heavy JS, OCR, fresh pages.",
      "  **T3 · Search APIs** — an index someone else already built; you query it instead of crawling.",
      "  **T4 · Licensed** — paid direct feeds (news, Q&A, code): expensive, but high-signal.",
    ],
    cardLabel: "AUTHORITY FIELD",
    aria: "A field of candidate domains placed by authority, with a green threshold ring.",
    steps: 2,
    captions: [
      "Each dot is a candidate domain, placed by authority — bigger and greener means higher.",
      "The ring keeps only domains above the threshold; the tier switches pick which sources they come from.",
    ],
    hint: "Drag the threshold — nytimes and medium drop out of the corpus around 85.",
    readoutTitle: "YIELD_METRICS",
    rows: ["ACCEPTED", "VOLUME", "SHOWN", "COST"],
    readoutNote: "The result of your cut: how many of the 2.4M candidate domains clear the bar, the monthly data volume, and the crawl cost.",
    sliderNote: "Authority = how many other sites link to this one. Raise the bar and you keep fewer, higher-quality domains — and pay less.",
    optionNotes: [
      "T1 · Common Crawl — the free public snapshot of the web. Most of the volume, none of the cost.",
      "T2 · In-house bots — the lab's own crawlers (GPTBot, ClaudeBot): heavy JavaScript, OCR, fresh pages.",
      "T3 · Search APIs — an index someone else already built; you query it instead of crawling.",
      "T4 · Licensed — paid direct feeds (news, Q&A, code). Expensive, but high-signal and legally clean.",
    ],
    ui: {
      slider: "MIN AUTHORITY",
      toggles: ["T1 · Common Crawl", "T2 · In-house bots", "T3 · Search APIs", "T4 · Licensed"],
    },
  },
  /* ------------------------------------------------ GATHER · 2 (web-scale N2) */
  {
    station: "gather",
    eyebrow: "GATHER · STEP 2",
    title: "How little of a page is actually text",
    intro: "A crawled page looks big, but almost none of it is prose a model can learn from. This is one real 104.6 KB page, every rectangle sized by its bytes.",
    bullets: [
      "**Scripts, CSS and markup dominate.** The actual sentences — the green cell — are about 10 KB, under 10% of the page.",
      "**[Common Crawl](https://commoncrawl.org) ships 3 versions:** WARC (everything), WAT (metadata), WET (just the text). Pre-training mostly uses WET.",
      "**Keeping the raw bytes buys nothing but provenance** — and a huge bill to download and unpack.",
    ],
    cardLabel: "ONE FETCHED PAGE · SIZED BY BYTES",
    aria: "A treemap of one web page, each block sized by its bytes; the prose is a small green block.",
    steps: 2,
    captions: [
      "The whole page: transport, scripts, markup, ads — every rectangle sized by bytes.",
      "Strip everything but the prose and about 10 KB is left — the part actually worth training on.",
    ],
    hint: "Switch WARC / WAT / WET — the readout shows what each version costs to download and unpack.",
    readoutTitle: "DATASET_TIER",
    rows: ["TRANSFER", "UNPACKED", "S3 COST", "DECODE"],
    readoutNote: "What one monthly snapshot costs in this format — download size and unpacked size (hosting is free on AWS Open Data).",
    optionNotes: [
      "WARC — the raw payload: headers + HTML + everything. Biggest, exact provenance, mostly noise.",
      "WAT — structured metadata (links, titles) as JSON. No page text.",
      "WET — extracted plain text only. Smallest, and what most pre-training actually uses.",
    ],
    ui: {
      segments: ["WARC", "WAT", "WET"],
      callout: {
        label: "GOOD TO KNOW · COMMON CRAWL",
        title: "A free 9-petabyte archive of the web",
        body: "Common Crawl is a non-profit that crawls the web every month and publishes it free on AWS Open Data — about 400 TiB per snapshot, 16+ years deep. It's the baseline almost every open model starts from.",
      },
    },
  },
  /* ------------------------------------------------ EXTRACT · 1 (web-scale N3) */
  {
    station: "extract",
    eyebrow: "EXTRACT & ENRICH · STEP 1",
    title: "From a saved page to training bytes",
    intro: "The last step showed how little of a page is text. This is the machine that extracts that text and turns it into something a GPU can train on — fast.",
    bullets: [
      "**A parser strips the page to clean text** — 104.6 KB of HTML in, about 18 KB of prose out.",
      "**Clean text → tokens → a memory-mapped `.bin`** that streams straight from disk (NVMe) into GPU memory (VRAM), with no re-parsing.",
      "**Parsing raw HTML during training would starve the GPUs**, so it's done once, up front.",
    ],
    cardLabel: "PAGE → PARSER → TOKENS → .BIN",
    aria: "A flow from a saved page through a parser to tokens and a .bin file, widths sized by bytes.",
    steps: 2,
    captions: [
      "One saved page enters the parser: 104.6 KB of HTML.",
      "The parser keeps about 18 KB of text; it's tokenised and written to a .bin that streams to the GPU.",
    ],
    hint: "Try the parsers — a crude regex keeps more, but the nav and ad junk it lets through ends up in your corpus.",
    readoutTitle: "PARSER_BENCHMARK",
    rows: ["IN", "OUT", "DROPPED", "CPU/PG"],
    readoutNote: "A per-page benchmark: bytes in, clean bytes out, and the share discarded as noise — multiplied across billions of pages.",
    optionNotes: [
      "Trafilatura — a purpose-built article extractor. Best at dropping nav and ads while keeping the text. The default.",
      "Resiliparse — also clean, and faster; tuned for throughput at web scale.",
      "Naive regex — just strips tags. Fast and simple, but leaves menus, ads and boilerplate in.",
    ],
    ui: {
      segments: ["Trafilatura", "Resiliparse", "Naive regex"],
    },
  },
  /* ------------------------------------------------ EXTRACT · 2 (domains N1) */
  {
    station: "extract",
    eyebrow: "EXTRACT & ENRICH · STEP 2",
    title: "Why mix in code and maths",
    intro: "Raw web text is mostly chatter — thin on step-by-step reasoning. Labs deliberately blend in denser sources, but the mix is a balancing act.",
    bullets: [
      "**Add code, maths and books.** They're a tiny slice of the web but carry the most logic and structure.",
      "**Keep 15–30% web text.** It keeps the model's everyday language natural — and holds [overfitting](https://en.wikipedia.org/wiki/Overfitting) at bay.",
      "**Don't overdo it.** Lean too hard on a small, specialised pile and the model re-reads it until it *memorises* it instead of learning the pattern.",
    ],
    cardLabel: "SET THE TRAINING MIX",
    aria: "The training mix and how often each pile is re-read",
    captions: ["The mix, its re-reads, and the reasoning it buys"],
    hint: "Drag Maths up: its small pile gets re-read past the 1.2× limit and the bar turns red — that's overfitting.",
    readoutTitle: "RECIPE",
    rows: ["Reasoning", "Web share", "Max re-reads", "Verdict"],
    readoutNote: "Aim for high reasoning while keeping web at or above 15% and re-reads under 1.2x.",
    ui: {
      presets: ["Default web", "Llama-3 style", "DeepSeek reasoner", "Extreme STEM"],
      domains: ["Web", "Code", "Maths", "Books"],
      callout: {
        label: "IN PLAIN WORDS",
        title: "Overfitting & epochs",
        body: "One full pass over the data is an *epoch*. Re-read a tiny pile many times and the model *memorises* it — like cramming answers instead of understanding — so labs cap re-reads and keep general web text in the mix.",
      },
      theMix: "THE MIX — share of training tokens",
      reReads: "TIMES EACH PILE IS RE-READ",
      overfit: "OVERFIT",
      safeLimit: "1.2x limit",
      reasoning: "REASONING",
      driftWarn: "web share below 15% — everyday language drifts",
      driftNote: "Web is only {web}% — below 15%, so the model's everyday language starts to drift.",
      overfitNote: "{name} is re-read {x}× — too small a pile, so the model memorises it (overfitting).",
      okNote: "Balanced: strong reasoning, no overfitting, and web text above 15%.",
    },
  },
  /* ------------------------------------------------ DEDUP · 1 (dedup N1) */
  {
    station: "dedup",
    eyebrow: "DEDUPLICATE · STEP 1",
    title: "Why repeated text destroys capacity",
    intro: "See a sentence 100 times in training and a model stops *learning* it and starts *memorising* it — prompt the opening words and it recites the rest verbatim. Deduplication is an information-density dial.",
    bullets: [
      "**Repeats over-index the weights.** Attention locks onto the exact token sequence, so the model regurgitates instead of reasoning — a privacy and copyright risk.",
      "**Removing duplicate bytes buys diversity.** In a fixed compute budget, every dropped repeat makes room for a *new* fact, code pattern, or argument.",
      "**The {ring} green gate drops copies before the weights.** Unique docs pass; byte-for-byte copies are filtered out up front.",
      "**Too aggressive and you clip *useful* repetition** — idioms, math identities, core syntax. The dial has a sweet spot.",
    ],
    cardLabel: "MEMORIZATION RISK · DEDUP GATE",
    aria: "A stream of documents flowing toward a model's weight matrix, with a green gate dropping duplicate copies.",
    steps: 2,
    captions: [
      "Duplicate documents (red) pour into the weight matrix; the connections stiffen into memorised, rigid paths.",
      "The green dedup gate drops the copies before they land — the weights relax into a balanced, general graph.",
    ],
    hint: "Duplicate copies (red) are blocked at the green gate; only the unique documents reach the weights.",
    readoutTitle: "MEMORIZATION_AUDIT",
    rows: ["DOCS KEPT", "VERBATIM", "COMPUTE SAVED", "UNIQUE"],
    readoutNote: "The audit of your cut: documents surviving, verbatim memorization rate (target < 0.1%), GPU hours saved, and how much unique text you preserved.",
  },
  /* ------------------------------------------------ DEDUP · 2 (dedup N5 · funnel) */
  {
    station: "dedup",
    eyebrow: "DEDUPLICATE · STEP 2",
    title: "The 3-stage dedup funnel",
    intro: "Dedup is a balancing act: strip too little and the model memorises; strip too much and you lose useful repetition. A staged funnel gets the density up while keeping enough volume.",
    bullets: [
      "**Each stage removes its slice at its own cost** — exact (fast CPU), fuzzy LSH (fast hash), semantic (GPU vectors).",
      "**Order matters:** cheap stages first, so the expensive GPU pass only sees what survived.",
      "**Aim for density, not maximum removal** — a pristine, high-reasoning-density corpus that still retains at least half its tokens.",
    ],
    cardLabel: "3-STAGE DEDUP FUNNEL",
    aria: "A three-tier funnel shrinking the dataset volume while a knowledge-density gauge rises.",
    steps: 1,
    captions: ["The raw dataset shrinks stage by stage while its knowledge-density gauge climbs into the green."],
    hint: "Toggle the three stages — each removes its slice; all three together hit high density while still retaining over half the volume.",
    readoutTitle: "FINAL_PIPELINE_SUMMARY",
    rows: ["INPUT", "OUTPUT", "DENSITY", "TIME"],
    readoutNote: "The whole funnel on 1 PB of raw crawl: input volume, output yield, knowledge-density score (0–100), and total cluster run time.",
    optionNotes: [
      "Stage 1 · Exact — drops ~15% of raw boilerplate and byte-identical files. Ultra-fast CPU.",
      "Stage 2 · Fuzzy LSH — drops ~20% of near-duplicate sites via MinHash + LSH. Fast hashing.",
      "Stage 3 · SemDeDup — drops ~10% of conceptual overlap via GPU embeddings. The costly polish.",
    ],
    ui: {
      toggles: ["Stage 1 · Exact", "Stage 2 · Fuzzy", "Stage 3 · Semantic"],
    },
  },
  /* ------------------------------------------------ RECIPE · 1 (recipe N1) */
  {
    station: "recipe",
    eyebrow: "THE RECIPE · STEP 1",
    title: "Why the natural web mix fails",
    intro: "The raw web is about 82% general chatter and almost no code or math. Train on it as-is and most of the model's capacity learns to autocomplete blog posts — so labs deliberately rewrite the mix.",
    bullets: [
      "**A data recipe is the exact % of tokens** from each domain a model sees — not the web's natural proportions, but a blend tuned for reasoning per compute dollar.",
      "**Density buys reasoning.** Code and maths are under 5% of the web but carry most of the multi-step logic signal, so labs {ring} upsample them hard.",
      "**But you can't starve general web text.** Drop it below ~15% and language itself degrades — idioms, world knowledge, fluency. Web text is the regularizer that keeps the model writing like a human.",
      "**Four presets to try** — scroll or tap them, then fine-tune the sliders.",
    ],
    cardLabel: "DOMAIN MIX · NATURAL vs YOUR RECIPE",
    aria: "Two stacked bars comparing the natural web domain mix against the target recipe you are building.",
    steps: 1,
    captions: ["The natural web mix beside the recipe you're building — reasoning density on one side, language health on the other."],
    hint: "Drag the four shares (they renormalise to 100%) or scroll the presets — push code + maths past 80% and linguistic drift trips.",
    readoutTitle: "RECIPE_METRICS",
    rows: ["REASONING", "LANGUAGE PPL", "MAX EPOCHS", "STATUS"],
    readoutNote: "Your mix scored: reasoning density (higher is better), held-out language perplexity (~11 is healthy, rises as web starves), and the safe epoch ceiling before scarce domains repeat too hard.",
    sliderNote: "Each share is a slice of the token budget; they renormalise to 100%. Web text is your language regularizer — keep it above ~15% or fluency degrades.",
    optionNotes: [
      "Raw unfiltered crawl — the web's natural proportions. Fluent, but almost no reasoning signal — the baseline everyone upsamples away from.",
      "Balanced recipe — a Llama-3-style blend: web trimmed to ~20%, code, maths and books lifted. High reasoning, language still healthy.",
      "Reasoner recipe — a DeepSeek-style push with even more code and maths. Sharp reasoning, but web is getting thin.",
      "Extreme STEM — code and maths crowd out everything. Reasoning peaks, but language drifts and the model forgets how to write a sentence.",
    ],
    ui: {
      presets: ["Raw crawl", "Balanced", "Reasoner", "Extreme STEM"],
      domains: ["Web", "Code", "Maths", "Books"],
      natural: "NATURAL WEB",
      yours: "YOUR RECIPE",
      driftWarn: "LINGUISTIC DRIFT · web text starved",
      driftNote: "Linguistic drift: general web text is too thin to hold language together. Reasoning may look high, but fluency, idioms and world knowledge are degrading — lift web back above ~15%.",
    },
  },
  /* ------------------------------------------------ RECIPE · 2 (recipe N4) */
  {
    station: "recipe",
    eyebrow: "THE RECIPE · STEP 2",
    title: "Manufacturing more high-density text",
    intro: "When the human supply of dense text runs dry, labs make more — a frontier model rewrites messy web pages into clean, textbook-style prose.",
    bullets: [
      "**Pick a messy seed** — a rambling blog post that contains real knowledge but reads like a forum comment.",
      "**A teacher model rewrites it** into a structured chapter: definitions, worked steps, exercises, clean code. Microsoft's [Phi](https://arxiv.org/abs/2306.11644) and Hugging Face's [Cosmopedia](https://huggingface.co/blog/cosmopedia) did exactly this.",
      "**One seed becomes many dense tokens** — the same facts at far higher {ring} educational density, for a teacher-API cost you can budget.",
    ],
    cardLabel: "WEB SEED → TEACHER MODEL → TEXTBOOK",
    aria: "A messy web seed beside the clean textbook chapter a teacher model generates from it.",
    steps: 2,
    captions: ["The uncurated seed on the left; the generated textbook chapter on the right — same topic, rebuilt for density."],
    hint: "Switch Paraphrase vs Full textbook rewrite — the same seed comes back richer or thinner.",
    readoutTitle: "GENERATION_YIELD",
    rows: ["SEED IN", "SYNTHETIC OUT", "DENSITY", "COST"],
    readoutNote: "The generation run: seed tokens in, synthetic tokens out, the educational-density score of the output, and the teacher-API bill against a $100k budget.",
    optionNotes: [
      "Simple paraphrase — reword the seed. Cheap, but it inherits the seed's gaps and adds little density.",
      "Full textbook rewrite — restructure into a self-contained chapter with definitions, steps and exercises. Higher density: the Phi approach.",
    ],
    ui: {
      segments: ["Simple paraphrase", "Full textbook rewrite"],
      seedLabel: "UNCURATED WEB SEED",
      outLabel: "SYNTHETIC TEXTBOOK · generated",
      paraphraseOut: "Dijkstra's algorithm finds shortest paths in a weighted graph using a min-heap / priority queue. It processes the nearest unvisited vertex first, relaxing its edges, until every distance is final.",
    },
  },
  /* ------------------------------------------------ RECIPE · 3 (recipe N6 · lock) */
  {
    station: "recipe",
    eyebrow: "THE RECIPE · STEP 3",
    title: "Locking the recipe",
    intro: "Real and synthetic streams are clean, deduplicated, and verified. The last step blends all five into one multi-trillion-token schedule the trainer reads start to finish.",
    bullets: [
      "**Five streams, one budget.** Web, code, maths, synthetic textbooks, and books / Q&A — each a fixed slice of a ~15-trillion-token schedule.",
      "**Synthetic now stands beside human data** — verified dense text earns a real share, not a footnote.",
      "**This is the hand-off to serialization:** the {ring} locked mix goes to pre-tokenization and binary serialization — the `.bin`/`.idx` files the GPUs stream.",
    ],
    cardLabel: "FINAL RECIPE · RAW WEB vs FRONTIER",
    aria: "Two stacked bars comparing the free raw-web mix against the final five-stream frontier recipe.",
    steps: 1,
    captions: ["What you'd get free from the raw web beside the recipe you engineered — same token budget, very different model."],
    hint: "Set the five shares (they renormalise to 100%) — aim for an estimated benchmark above 88 while keeping web as the language anchor.",
    readoutTitle: "MASTER_RECIPE",
    rows: ["TOTAL", "EST. BENCHMARK", "EFFICIENCY", "STATUS"],
    readoutNote: "Your locked mix mapped onto 15 trillion tokens: the estimated benchmark score, compute efficiency (reasoning per FLOP), and whether it's cleared for training.",
    sliderNote: "Each slider is a stream's share of the 15T-token budget; they renormalise to 100%. Synthetic and code/maths lift the benchmark; web keeps the language grounded.",
    ui: {
      streams: ["Web", "Code", "Maths", "Synthetic", "Books"],
      rawLabel: "RAW WEB · free",
      finalLabel: "FRONTIER RECIPE",
    },
  },
];

const NODES_ES: PipelineNode[] = [
  /* ------------------------------------------------ GATHER · 1 (web-scale N1) */
  {
    station: "gather",
    eyebrow: "RECOLECTAR · PASO 1",
    title: "Qué dominios llegan siquiera a rastrearse",
    intro: "No puedes rastrear toda la web con un presupuesto fijo — así que antes de descargar nada, un laboratorio ordena los dominios por autoridad y conserva solo la mejor porción.",
    bullets: [
      "**La autoridad es una puntuación estilo [PageRank](https://es.wikipedia.org/wiki/PageRank)** sobre los enlaces entrantes. Los grandes hubs — [Wikipedia](https://es.wikipedia.org/wiki/Wikipedia), GitHub, arXiv — quedan cerca del centro.",
      "**El anillo verde {ring} es el umbral.** Dentro se conserva como semilla; fuera se descarta *antes de bajar un solo byte* — el número de mayor impacto del pipeline.",
      "**Las páginas vienen de 4 niveles** — activa cada uno abajo:",
      "  **T1 · Common Crawl** — la instantánea pública y gratis de la web. Casi todo el volumen, sin costo.",
      "  **T2 · Bots propios** — los rastreadores del laboratorio (GPTBot, ClaudeBot): mucho JS, OCR, páginas frescas.",
      "  **T3 · APIs de búsqueda** — un índice que alguien ya construyó; lo consultas en vez de rastrear.",
      "  **T4 · Licenciado** — feeds directos de pago (noticias, preguntas, código): caros, pero de alta señal.",
    ],
    cardLabel: "CAMPO DE AUTORIDAD",
    aria: "Un campo de dominios candidatos ubicados por autoridad, con un anillo verde de umbral.",
    steps: 2,
    captions: [
      "Cada punto es un dominio candidato, ubicado por autoridad — más grande y más verde = más alto.",
      "El anillo conserva solo los dominios sobre el umbral; los interruptores eligen de qué fuentes vienen.",
    ],
    hint: "Arrastra el umbral — nytimes y medium salen del corpus alrededor de 85.",
    readoutTitle: "YIELD_METRICS",
    rows: ["ACEPTADOS", "VOLUMEN", "VISIBLES", "COSTO"],
    readoutNote: "El resultado de tu corte: cuántos de los 2.4M dominios candidatos superan la barra, el volumen mensual y el costo de rastreo.",
    sliderNote: "Autoridad = cuántos otros sitios enlazan a este. Sube la barra y conservas menos dominios, pero de más calidad — y pagas menos.",
    optionNotes: [
      "T1 · Common Crawl — la instantánea pública y gratis de la web. Casi todo el volumen, sin costo.",
      "T2 · Bots propios — los rastreadores del laboratorio (GPTBot, ClaudeBot): mucho JavaScript, OCR, páginas frescas.",
      "T3 · APIs de búsqueda — un índice que alguien ya construyó; lo consultas en vez de rastrear.",
      "T4 · Licenciado — feeds directos de pago (noticias, preguntas, código). Caros, pero de alta señal y legalmente limpios.",
    ],
    ui: {
      slider: "MIN AUTHORITY",
      toggles: ["T1 · Common Crawl", "T2 · Bots propios", "T3 · APIs de búsqueda", "T4 · Licenciado"],
    },
  },
  /* ------------------------------------------------ GATHER · 2 (web-scale N2) */
  {
    station: "gather",
    eyebrow: "RECOLECTAR · PASO 2",
    title: "Qué tan poco de una página es texto",
    intro: "Una página rastreada parece grande, pero casi nada de ella es prosa de la que un modelo pueda aprender. Esta es una página real de 104.6 KB, cada rectángulo dimensionado por sus bytes.",
    bullets: [
      "**Scripts, CSS y marcado dominan.** Las frases de verdad — la celda verde — son unos 10 KB, menos del 10% de la página.",
      "**[Common Crawl](https://commoncrawl.org) publica 3 versiones:** WARC (todo), WAT (metadatos), WET (solo el texto). El preentrenamiento usa sobre todo WET.",
      "**Conservar los bytes crudos no compra nada salvo procedencia** — y una factura enorme para descargar y descomprimir.",
    ],
    cardLabel: "UNA PÁGINA · DIMENSIONADA POR BYTES",
    aria: "Un treemap de una página web, cada bloque dimensionado por sus bytes; la prosa es un bloque verde pequeño.",
    steps: 2,
    captions: [
      "La página entera: transporte, scripts, marcado, anuncios — cada rectángulo dimensionado por bytes.",
      "Quita todo salvo la prosa y quedan unos 10 KB — la parte que de verdad vale la pena entrenar.",
    ],
    hint: "Cambia WARC / WAT / WET — el panel muestra lo que cuesta descargar y descomprimir cada versión.",
    readoutTitle: "DATASET_TIER",
    rows: ["TRANSFER", "UNPACKED", "S3 COST", "DECODE"],
    readoutNote: "Lo que cuesta una instantánea mensual en este formato — tamaño de descarga y tamaño descomprimido (el alojamiento es gratis en AWS Open Data).",
    optionNotes: [
      "WARC — el payload crudo: cabeceras + HTML + todo. El más grande, procedencia exacta, casi todo ruido.",
      "WAT — metadatos estructurados (enlaces, títulos) en JSON. Sin texto de la página.",
      "WET — solo el texto plano extraído. El más pequeño, y lo que usa casi todo el preentrenamiento.",
    ],
    ui: {
      segments: ["WARC", "WAT", "WET"],
      callout: {
        label: "PARA SABER · COMMON CRAWL",
        title: "Un archivo gratis de 9 petabytes de la web",
        body: "Common Crawl es una organización sin fines de lucro que rastrea la web cada mes y la publica gratis en AWS Open Data — unos 400 TiB por instantánea, con 16+ años de profundidad. Es la base de la que parte casi todo modelo abierto.",
      },
    },
  },
  /* ------------------------------------------------ EXTRACT · 1 (web-scale N3) */
  {
    station: "extract",
    eyebrow: "EXTRAER Y ENRIQUECER · PASO 1",
    title: "De una página guardada a bytes de entrenamiento",
    intro: "El paso anterior mostró qué poco de una página es texto. Esta es la máquina que extrae ese texto y lo convierte en algo que una GPU puede entrenar — rápido.",
    bullets: [
      "**Un parser reduce la página a texto limpio** — entran 104.6 KB de HTML, salen unos 18 KB de prosa.",
      "**Texto limpio → tokens → un `.bin` mapeado en memoria** que fluye del disco (NVMe) a la memoria de la GPU (VRAM), sin re-parsear.",
      "**Parsear HTML crudo durante el entrenamiento dejaría a las GPU en ayunas**, así que se hace una sola vez, por adelantado.",
    ],
    cardLabel: "PÁGINA → PARSER → TOKENS → .BIN",
    aria: "Un flujo de una página guardada por un parser hacia tokens y un archivo .bin, anchos dimensionados por bytes.",
    steps: 2,
    captions: [
      "Una página guardada entra al parser: 104.6 KB de HTML.",
      "El parser conserva unos 18 KB de texto; se tokeniza y se escribe a un .bin que fluye a la GPU.",
    ],
    hint: "Prueba los parsers — un regex tosco conserva más, pero la basura de nav y anuncios que deja pasar acaba en tu corpus.",
    readoutTitle: "PARSER_BENCHMARK",
    rows: ["IN", "OUT", "DROPPED", "CPU/PG"],
    readoutNote: "Un benchmark por página: bytes de entrada, bytes limpios de salida y la porción descartada como ruido — multiplicado por miles de millones de páginas.",
    optionNotes: [
      "Trafilatura — un extractor de artículos hecho a propósito. El mejor para quitar nav y anuncios y conservar el texto. El predeterminado.",
      "Resiliparse — también limpio, y más rápido; ajustado para rendimiento a escala web.",
      "Regex ingenuo — solo quita etiquetas. Rápido y simple, pero deja menús, anuncios y plantillas.",
    ],
    ui: {
      segments: ["Trafilatura", "Resiliparse", "Regex ingenuo"],
    },
  },
  /* ------------------------------------------------ EXTRACT · 2 (domains N1) */
  {
    station: "extract",
    eyebrow: "EXTRAER Y ENRIQUECER · PASO 2",
    title: "Por qué mezclar código y matemáticas",
    intro: "El texto web crudo es sobre todo charla — pobre en razonamiento paso a paso. Los laboratorios mezclan a propósito fuentes más densas, pero la mezcla es un equilibrio delicado.",
    bullets: [
      "**Añade código, matemáticas y libros.** Son una porción diminuta de la web pero cargan la mayor parte de la lógica y la estructura.",
      "**Deja 15–30% de texto web.** Mantiene natural el lenguaje cotidiano del modelo — y frena el [sobreajuste](https://es.wikipedia.org/wiki/Sobreajuste).",
      "**No te excedas.** Si abusas de un montón pequeño y especializado, el modelo lo relee hasta *memorizarlo* en vez de aprender el patrón.",
    ],
    cardLabel: "AJUSTA LA MEZCLA",
    aria: "La mezcla de entrenamiento y cuántas veces se relee cada montón",
    captions: ["La mezcla, sus relecturas y el razonamiento que compra"],
    hint: "Sube Matemáticas: su montón pequeño se relee más de 1.2x y la barra se pone roja — eso es sobreajuste.",
    readoutTitle: "RECETA",
    rows: ["Razonamiento", "Cuota web", "Máx. relecturas", "Veredicto"],
    readoutNote: "Busca alto razonamiento manteniendo web en 15% o más y relecturas por debajo de 1.2x.",
    ui: {
      presets: ["Web por defecto", "Estilo Llama-3", "DeepSeek reasoner", "STEM extremo"],
      domains: ["Web", "Código", "Matemát.", "Libros"],
      callout: {
        label: "EN PALABRAS SIMPLES",
        title: "Sobreajuste y épocas",
        body: "Una pasada completa por los datos es una *época*. Releer un montón pequeño muchas veces hace que el modelo lo *memorice* — como empollar respuestas en vez de entender — así que los laboratorios limitan las relecturas y dejan texto web en la mezcla.",
      },
      theMix: "LA MEZCLA — cuota de tokens de entrenamiento",
      reReads: "VECES QUE SE RELEE CADA MONTÓN",
      overfit: "SOBREAJUSTE",
      safeLimit: "límite 1.2x",
      reasoning: "RAZONAMIENTO",
      driftWarn: "cuota web bajo 15% — el lenguaje cotidiano deriva",
      driftNote: "La web es solo el {web}% — por debajo del 15%, así que el lenguaje cotidiano del modelo empieza a derivar.",
      overfitNote: "{name} se relee {x}× — un montón demasiado pequeño, así que el modelo lo memoriza (sobreajuste).",
      okNote: "Equilibrado: buen razonamiento, sin sobreajuste y con texto web por encima del 15%.",
    },
  },
  /* ------------------------------------------------ DEDUP · 1 (dedup N1) */
  {
    station: "dedup",
    eyebrow: "DEDUPLICAR · PASO 1",
    title: "Por qué el texto repetido destruye capacidad",
    intro: "Si una frase aparece 100 veces en el entrenamiento, el modelo deja de *aprenderla* y empieza a *memorizarla* — dale las primeras palabras y recita el resto textual. La deduplicación es un dial de densidad de información.",
    bullets: [
      "**Las repeticiones sobreindexan los pesos.** La atención se fija en la secuencia exacta de tokens, así que el modelo regurgita en vez de razonar — un riesgo de privacidad y de copyright.",
      "**Quitar bytes duplicados compra diversidad.** En un presupuesto fijo de cómputo, cada repetición eliminada deja sitio para un dato, patrón de código o argumento *nuevo*.",
      "**El portón verde {ring} descarta las copias antes de los pesos.** Los documentos únicos pasan; las copias byte a byte se filtran de entrada.",
      "**Demasiado agresivo y recortas repetición *útil*** — modismos, identidades matemáticas, sintaxis básica. El dial tiene un punto óptimo.",
    ],
    cardLabel: "RIESGO DE MEMORIA · PORTÓN DEDUP",
    aria: "Un flujo de documentos hacia la matriz de pesos de un modelo, con un portón verde que descarta las copias duplicadas.",
    steps: 2,
    captions: [
      "Los documentos duplicados (rojo) entran en la matriz de pesos; las conexiones se endurecen en rutas rígidas memorizadas.",
      "El portón verde de dedup descarta las copias antes de que lleguen — los pesos se relajan en un grafo general equilibrado.",
    ],
    hint: "Las copias duplicadas (rojo) se bloquean en el portón verde; solo los documentos únicos llegan a los pesos.",
    readoutTitle: "AUDITORÍA_MEMORIA",
    rows: ["DOCS QUEDAN", "TEXTUAL", "CÓMPUTO AHORR.", "ÚNICOS"],
    readoutNote: "La auditoría de tu corte: documentos que sobreviven, tasa de memorización textual (objetivo < 0.1%), horas de GPU ahorradas y cuánto texto único preservaste.",
  },
  /* ------------------------------------------------ DEDUP · 2 (dedup N5 · funnel) */
  {
    station: "dedup",
    eyebrow: "DEDUPLICAR · PASO 2",
    title: "El embudo de deduplicación de 3 etapas",
    intro: "La dedup es un equilibrio: quita muy poco y el modelo memoriza; quita demasiado y pierdes repetición útil. Un embudo por etapas sube la densidad conservando volumen suficiente.",
    bullets: [
      "**Cada etapa quita su porción a su propio costo** — exacta (CPU rápida), LSH difusa (hash rápido), semántica (vectores de GPU).",
      "**El orden importa:** las etapas baratas primero, para que la pasada cara de GPU solo vea lo que sobrevivió.",
      "**Apunta a densidad, no a máxima remoción** — un corpus prístino de alta densidad de razonamiento que aún retiene al menos la mitad de sus tokens.",
    ],
    cardLabel: "EMBUDO DEDUP DE 3 ETAPAS",
    aria: "Un embudo de tres niveles que encoge el volumen del conjunto mientras sube un indicador de densidad de conocimiento.",
    steps: 1,
    captions: ["El conjunto crudo se encoge etapa a etapa mientras su indicador de densidad de conocimiento sube hacia el verde."],
    hint: "Alterna las tres etapas — cada una quita su porción; las tres juntas alcanzan alta densidad reteniendo aún más de la mitad del volumen.",
    readoutTitle: "RESUMEN_FINAL_PIPELINE",
    rows: ["ENTRADA", "SALIDA", "DENSIDAD", "TIEMPO"],
    readoutNote: "El embudo completo sobre 1 PB de crawl crudo: volumen de entrada, rendimiento de salida, puntaje de densidad de conocimiento (0–100) y tiempo total de cómputo.",
    optionNotes: [
      "Etapa 1 · Exacta — quita ~15% de plantilla cruda y archivos idénticos byte a byte. CPU ultrarrápida.",
      "Etapa 2 · LSH difusa — quita ~20% de sitios casi duplicados vía MinHash + LSH. Hashing rápido.",
      "Etapa 3 · SemDeDup — quita ~10% de solape conceptual vía embeddings de GPU. El pulido costoso.",
    ],
    ui: {
      toggles: ["Etapa 1 · Exacta", "Etapa 2 · Difusa", "Etapa 3 · Semántica"],
    },
  },
  /* ------------------------------------------------ RECIPE · 1 (recipe N1) */
  {
    station: "recipe",
    eyebrow: "LA RECETA · PASO 1",
    title: "Por qué falla la mezcla natural de la web",
    intro: "La web cruda es cerca del 82% de charla general y casi nada de código o matemáticas. Entrena con ella tal cual y la mayor parte de la capacidad del modelo aprende a autocompletar posts de blog — por eso los laboratorios reescriben la mezcla a propósito.",
    bullets: [
      "**Una receta de datos es el % exacto de tokens** de cada dominio que ve un modelo — no las proporciones naturales de la web, sino una mezcla ajustada para razonar por dólar de cómputo.",
      "**La densidad compra razonamiento.** Código y matemáticas son menos del 5% de la web pero cargan la mayor parte de la señal de lógica de varios pasos, así que los laboratorios los {ring} sobremuestrean con fuerza.",
      "**Pero no puedes matar de hambre al texto web general.** Bájalo del ~15% y el lenguaje mismo se degrada — modismos, conocimiento del mundo, fluidez. El texto web es el regularizador que mantiene al modelo escribiendo como un humano.",
      "**Cuatro presets para probar** — desplázate o tócalos, luego ajusta los deslizadores.",
    ],
    cardLabel: "MEZCLA DE DOMINIOS · NATURAL vs TU RECETA",
    aria: "Dos barras apiladas que comparan la mezcla natural de dominios de la web con la receta objetivo que estás construyendo.",
    steps: 1,
    captions: ["La mezcla natural de la web junto a la receta que construyes — densidad de razonamiento de un lado, salud del lenguaje del otro."],
    hint: "Arrastra las cuatro cuotas (se renormalizan a 100%) o desplaza los presets — sube código + matemáticas por encima del 80% y se dispara la deriva lingüística.",
    readoutTitle: "MÉTRICAS_RECETA",
    rows: ["RAZONAMIENTO", "PPL LENGUAJE", "ÉPOCAS MÁX", "ESTADO"],
    readoutNote: "Tu mezcla puntuada: densidad de razonamiento (más es mejor), perplejidad del lenguaje en validación (~11 es sano, sube cuando la web se adelgaza) y el techo seguro de épocas antes de que los dominios escasos se repitan demasiado.",
    sliderNote: "Cada cuota es una porción del presupuesto de tokens; se renormalizan a 100%. El texto web es tu regularizador del lenguaje — mantenlo por encima del ~15% o la fluidez se degrada.",
    optionNotes: [
      "Rastreo crudo sin filtrar — las proporciones naturales de la web. Fluido, pero casi sin señal de razonamiento — la base de la que todos se alejan sobremuestreando.",
      "Receta equilibrada — una mezcla estilo Llama-3: web recortada al ~20%, con más código, matemáticas y libros. Razonamiento alto, lenguaje aún sano.",
      "Receta razonadora — un empuje estilo DeepSeek con aún más código y matemáticas. Razonamiento afilado, pero la web se adelgaza.",
      "STEM extremo — código y matemáticas desplazan todo lo demás. El razonamiento llega al tope, pero el lenguaje deriva y el modelo olvida cómo escribir una frase.",
    ],
    ui: {
      presets: ["Rastreo crudo", "Equilibrada", "Razonadora", "STEM extremo"],
      domains: ["Web", "Código", "Mates", "Libros"],
      natural: "WEB NATURAL",
      yours: "TU RECETA",
      driftWarn: "DERIVA LINGÜÍSTICA · web famélica",
      driftNote: "Deriva lingüística: el texto web general es demasiado escaso para sostener el lenguaje. El razonamiento puede verse alto, pero la fluidez, los modismos y el conocimiento del mundo se degradan — sube la web por encima del ~15%.",
    },
  },
  /* ------------------------------------------------ RECIPE · 2 (recipe N4) */
  {
    station: "recipe",
    eyebrow: "LA RECETA · PASO 2",
    title: "Fabricar más texto de alta densidad",
    intro: "Cuando la oferta humana de texto denso se seca, los laboratorios hacen más — un modelo puntero reescribe páginas web desordenadas en prosa limpia de estilo libro de texto.",
    bullets: [
      "**Elige una semilla desordenada** — un post de blog divagante que contiene conocimiento real pero se lee como un comentario de foro.",
      "**Un modelo maestro lo reescribe** en un capítulo estructurado: definiciones, pasos resueltos, ejercicios, código limpio. [Phi](https://arxiv.org/abs/2306.11644) de Microsoft y [Cosmopedia](https://huggingface.co/blog/cosmopedia) de Hugging Face hicieron justo esto.",
      "**Una semilla se vuelve muchos tokens densos** — los mismos hechos con mucha mayor {ring} densidad educativa, por un costo de API del maestro que puedes presupuestar.",
    ],
    cardLabel: "SEMILLA WEB → MODELO MAESTRO → LIBRO DE TEXTO",
    aria: "Una semilla web desordenada junto al capítulo limpio de libro de texto que un modelo maestro genera a partir de ella.",
    steps: 2,
    captions: ["La semilla sin curar a la izquierda; el capítulo de libro de texto generado a la derecha — mismo tema, reconstruido para densidad."],
    hint: "Cambia entre Parafraseo y Reescritura completa — la misma semilla vuelve más rica o más pobre.",
    readoutTitle: "RENDIMIENTO_GENERACIÓN",
    rows: ["SEMILLA", "SINTÉTICO", "DENSIDAD", "COSTO"],
    readoutNote: "La corrida de generación: tokens semilla que entran, tokens sintéticos que salen, la puntuación de densidad educativa de la salida, y la factura de API del maestro frente a un presupuesto de $100k.",
    optionNotes: [
      "Parafraseo simple — reformular la semilla. Barato, pero hereda los huecos de la semilla y añade poca densidad.",
      "Reescritura completa — reestructurar en un capítulo autocontenido con definiciones, pasos y ejercicios. Mayor densidad: el enfoque de Phi.",
    ],
    ui: {
      segments: ["Parafraseo simple", "Reescritura completa"],
      seedLabel: "SEMILLA WEB SIN CURAR",
      outLabel: "LIBRO DE TEXTO SINTÉTICO · generado",
      paraphraseOut: "El algoritmo de Dijkstra encuentra los caminos más cortos en un grafo ponderado usando un min-heap / cola de prioridad. Procesa primero el vértice no visitado más cercano, relajando sus aristas, hasta que cada distancia es definitiva.",
    },
  },
  /* ------------------------------------------------ RECIPE · 3 (recipe N6 · lock) */
  {
    station: "recipe",
    eyebrow: "LA RECETA · PASO 3",
    title: "Fijar la receta",
    intro: "Los flujos reales y sintéticos están limpios, deduplicados y verificados. El último paso mezcla los cinco en un solo calendario de billones de tokens que el entrenador lee de principio a fin.",
    bullets: [
      "**Cinco flujos, un presupuesto.** Web, código, matemáticas, libros de texto sintéticos y libros / preguntas-respuestas — cada uno una porción fija de un calendario de ~15 billones de tokens.",
      "**Lo sintético ahora se codea con los datos humanos** — el texto denso verificado gana una cuota real, no una nota al pie.",
      "**Este es el relevo a la serialización:** la {ring} mezcla fijada pasa a la pre-tokenización y la serialización binaria — los archivos `.bin`/`.idx` que las GPUs transmiten.",
    ],
    cardLabel: "RECETA FINAL · WEB CRUDA vs FRONTERA",
    aria: "Dos barras apiladas que comparan la mezcla gratuita de web cruda con la receta final de frontera de cinco flujos.",
    steps: 1,
    captions: ["Lo que obtendrías gratis de la web cruda junto a la receta que diseñaste — mismo presupuesto de tokens, un modelo muy distinto."],
    hint: "Fija las cinco cuotas (se renormalizan a 100%) — apunta a un benchmark estimado sobre 88 manteniendo la web como ancla del lenguaje.",
    readoutTitle: "RECETA_MAESTRA",
    rows: ["TOTAL", "BENCHMARK EST.", "EFICIENCIA", "ESTADO"],
    readoutNote: "Tu mezcla fijada mapeada sobre 15 billones de tokens: la puntuación de benchmark estimada, la eficiencia de cómputo (razonamiento por FLOP) y si está aprobada para entrenar.",
    sliderNote: "Cada deslizador es la cuota de un flujo del presupuesto de 15 B de tokens; se renormalizan a 100%. Lo sintético y código/matemáticas suben el benchmark; la web mantiene el lenguaje anclado.",
    ui: {
      streams: ["Web", "Código", "Mates", "Sintético", "Libros"],
      rawLabel: "WEB CRUDA · gratis",
      finalLabel: "RECETA DE FRONTERA",
    },
  },
];

export const dataPipelineEN: PipelineLesson = {
  crumb: "STAGE 0 · THE DATA PIPELINE · PART 1",
  eyebrow: "STAGE 0 · THE DATA PIPELINE · PART 1",
  title: "From the whole internet to a recipe",
  lede: "Nobody trains a model on the raw web. Follow the four stations that turn the open internet into a small, clean, carefully-blended training recipe — gather, extract, deduplicate, mix. Play with each step.",
  mapLabel: "THE PIPELINE",
  stations: STATIONS_EN,
  explainLabel: "EXPLAIN IT BACK",
  explainQ: "The web is free and nearly infinite. Why spend so much engineering to shrink, clean and re-blend it instead of just training on all of it?",
  explainA: "Because raw size isn't the goal — **density** is. Most of the web is boilerplate, duplicates and chatter; train on it as-is and the model learns to autocomplete blog spam. Each station raises the *information per token*: authority-ranking keeps the good domains, extraction pulls the real text and adds reasoning-dense sources, dedup deletes the repeats that cause memorisation, and the recipe up-weights code and maths and tops up with synthetic text. The output is a **smaller** pile that teaches far more per compute dollar.",
  bridgeLabel: "NEXT: PART 2 · INSIDE THE PIPELINE",
  bridgeBody: "You've walked the whole pipeline end to end. **Part 2 opens each station up** — the robots.txt and copyright rules, the code and PDF cleanup, the three dedup algorithms, and the temperature and epoch knobs that tune the recipe. Same four stations, one level deeper.",
  prevLabel: "Back to the roadmap",
  prevHref: "/",
  nextLabel: "Continue to Part 2",
  nextHref: "/stage/0/data-pipeline-deep",
  nodes: NODES_EN,
};

export const dataPipelineES: PipelineLesson = {
  crumb: "ETAPA 0 · EL PIPELINE DE DATOS · PARTE 1",
  eyebrow: "ETAPA 0 · EL PIPELINE DE DATOS · PARTE 1",
  title: "De todo el internet a una receta",
  lede: "Nadie entrena un modelo con la web cruda. Sigue las cuatro estaciones que convierten el internet abierto en una receta de entrenamiento pequeña, limpia y cuidadosamente mezclada — recolectar, extraer, deduplicar, mezclar. Juega con cada paso.",
  mapLabel: "EL PIPELINE",
  stations: STATIONS_ES,
  explainLabel: "EXPLÍCALO CON TUS PALABRAS",
  explainQ: "La web es gratis y casi infinita. ¿Por qué gastar tanta ingeniería en reducirla, limpiarla y re-mezclarla en vez de entrenar con todo?",
  explainA: "Porque el objetivo no es el tamaño crudo — es la **densidad**. Casi toda la web es plantilla, duplicados y charla; entrena con ella tal cual y el modelo aprende a autocompletar spam de blogs. Cada estación sube la *información por token*: el orden por autoridad conserva los buenos dominios, la extracción saca el texto real y añade fuentes densas en razonamiento, la deduplicación borra las repeticiones que causan memorización, y la receta sube el peso de código y matemáticas y completa con texto sintético. El resultado es un montón **más pequeño** que enseña mucho más por cada dólar de cómputo.",
  bridgeLabel: "SIGUIENTE: PARTE 2 · DENTRO DEL PIPELINE",
  bridgeBody: "Ya recorriste todo el pipeline de principio a fin. **La Parte 2 abre cada estación** — las reglas de robots.txt y copyright, la limpieza de código y PDFs, los tres algoritmos de deduplicación, y las perillas de temperatura y épocas que afinan la receta. Las mismas cuatro estaciones, un nivel más profundo.",
  prevLabel: "Volver a la ruta",
  prevHref: "/",
  nextLabel: "Continuar a la Parte 2",
  nextHref: "/stage/0/data-pipeline-deep",
  nodes: NODES_ES,
};
